export const Users = [
   {
     id:1,
     profilePicture: "person/person1.jpeg",
     username: "Anastasia Kozlova",
   },
   {
     id:2,
     profilePicture: "person/person9.jpeg",
     username: "Evgeny Bulichev",
   },
   {
     id:3,
     profilePicture: "person/person3.jpeg",
     username: "Verinika Samoylova",
   },
   {
     id:4,
     profilePicture: "person/person4.jpeg",
     username: "Maria Tihonova",
   },
   {
     id:5,
     profilePicture: "person/person7.jpeg",
     username: "Alexsandr Mironov",
   },
   {
     id:6,
     profilePicture: "person/person5.jpeg",
     username: "Anna Borodach",
   },
   {
     id:7,
     profilePicture: "person/person6.jpeg",
     username: "Vasilisa Ampermetrova",
   },
   {
     id:8,
     profilePicture: "person/person8.jpeg",
     username: "Pank Dots",
   },
   {
     id:9,
     profilePicture: "person/person11.jpeg",
     username: "Maksim Andreev",
   },
   {
     id:10,
     profilePicture: "person/person10.jpeg",
     username: "Valeria Smirnaya",
   },
 ];
 
 export const Posts = [
   {
     id: 1,
     desc: "The meaning of life is to die young ... as late as possible.",
     photo: "posts/post3.jpeg",
     date: "5 mins ago",
     userId: 1,
     like: 32,
     comment: 9,
   },
   {
     id: 2,
     photo: "posts/post2.jpeg",
     date: "15 mins ago",
     userId: 2,
     like: 2,
     comment: 1,
   },
   {
     id: 3,
     desc: "Friday is my second favorite word.",
     photo: "posts/post1.jpeg",
     date: "1 hour ago",
     userId: 3,
     like: 61,
     comment: 2,
   },
   {
     id: 4,
     photo: "posts/post4.jpeg",
     date: "4 hours ago",
     userId: 4,
     like: 7,
     comment: 3,
   },
   {
     id: 5,
     photo: "posts/post5.jpeg",
     date: "5 hours ago",
     userId: 5,
     like: 23,
     comment: 5,
   },
   {
     id: 6,
     decs: "Say yes to new adventures.",
     photo: "posts/post6.jpeg",
     date: "1 day ago",
     userId: 6,
     like: 44,
     comment: 6,
   },
   {
     id: 7,
     desc: "Rest so that you forget to pick up your phone.",
     photo: "posts/post7.jpeg",
     date: "2 days ago",
     userId: 7,
     like: 52,
     comment: 3,
   },
   {
     id: 8,
     photo: "posts/post8.jpeg",
     date: "3 days ago",
     userId: 8,
     like: 15,
     comment: 1,
   },
   {
     id: 9,
     desc: "I'm normal, the boys told me so",
     photo: "posts/post9.jpeg",
     date: "5 days ago",
     userId: 9,
     like: 11,
     comment: 2,
   },
   {
     id: 10,
     photo: "posts/post10.jpeg",
     date: "1 week ago",
     userId: 10,
     like: 104,
     comment: 12,
   },
 ];